name: Quality Checks
on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]
jobs:
  runsLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: pip install pytest pytest-cov flake8 mypy pydocstyle
      - name: Run test cases
        run: python -m pytest --cov-report xml --cov-report term --cov-report html --cov .
      - name: Check formatting style
        run: python -m flake8 --count
      - name: Check type hints
        run: python -m mypy
      - name: Check documentation
        run: python -m pydocstyle
